version: '3.8'

services:
  database:
    image: postgres:16
    container_name: ecommers_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
     - ../pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: . 
    image: ecommers-backend  
    container_name: ecommers-backend
    depends_on:
      - database
    ports:
      - "3000:3000"  
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_TYPE: postgres
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped